-- Your SQL goes here
CREATE TABLE tweets (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  message TEXT NOT NULL
);

CREATE TABLE likes (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  tweet_id INTEGER NULL
);